version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit
  ui:
    image: ${USERNAME}/ui:1.0
    ports:
      - "9292:9292/tcp"
    networks:
      - reddit
  post:
    image: ${USERNAME}/post:1.0
    networks:
      - reddit
  comment:
    image: ${USERNAME}/comment:1.0
    networks:
      - reddit

volumes:
  post_db:

networks:
  reddit:
